version: '3'

services:
  vegabot:
    container_name: lfgbot
    build:
      context: .
    restart: on-failure
    environment:
      - TG_API_KEY
      - TG_CHAT_ID
    volumes:
      - ./app:/app
    links:
      - mongo
  mongo:
    image: mongo:4.0.4
    restart: always
